# SPDX-FileCopyrightText: 2017 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: CC0-1.0
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
