# SPDX-FileCopyrightText: 2019 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

site_name: Nextcloud Talk API documentation

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php
    - js
    - bash

markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: "#"
      baselevel: 2

nav:
  - 'Overview': 'index.md'
  - 'User documentation':
      - 'User system requirements': 'user-requirements.md'
      - 'User feature documentation ↗': 'https://docs.nextcloud.com/server/latest/user_manual/en/talk/index.html'
  - 'Administration documentation':
      - 'Server system requirements': 'system-requirements.md'
      - 'Quick install': 'quick-install.md'
      - 'Scalability': 'scalability.md'
      - 'Call experience': 'call-experience.md'
      - 'Sample conversations': 'sample-conversations.md'
      - 'Occ commands': 'occ.md'
      - 'Bots': 'bot-list.md'
      - 'Matterbridge integration': 'matterbridge.md'
  - 'Developer documentation':
      - 'Developer setup': 'developer-setup.md'
      - 'Bots and webhooks': 'bots.md'
      - 'Constants': 'constants.md'
      - 'Capabilities': 'capabilities.md'
      - 'PHP events': 'events.md'
  - 'API documentation':
      - 'Global API status and headers': 'global.md'
      - 'Conversations management': 'conversation.md'
      - 'Conversation avatars management': 'avatar.md'
      - 'Participants management': 'participant.md'
      - 'Call management': 'call.md'
      - 'Call recording management': 'recording.md'
      - 'Chat management': 'chat.md'
      - 'Reaction management': 'reaction.md'
      - 'Poll management': 'poll.md'
      - 'Breakout rooms management': 'breakout-rooms.md'
      - 'Bots management': 'bot-management.md'
      - 'Integration by other apps': 'integration.md'
      - 'Webinar management': 'webinar.md'
      - 'Settings management': 'settings.md'
      - 'Internal Signaling API': 'internal-signaling.md'
      - 'Standalone Signaling API↗': 'https://nextcloud-spreed-signaling.readthedocs.io/en/latest/'
  - 'Configuring a TURN server':
      - 'Overview': 'TURN.md'
      - 'coTURN': 'coturn.md'
      - 'eturnal': 'eturnal.md'
  - 'Removed features':
      - 'Commands': 'commands.md'
