name: ChatGPT Codex Analyzer

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Ветка для анализа"
        required: true
        default: "OriginalCode/2.0.1-beta"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Collect file list
        id: list
        run: |
          echo "🔍 Собираю список файлов..."
          find . -type f \( -name "*.js" -o -name "*.ts" -o -name "*.py" -o -name "*.json" -o -name "*.md" \) > filelist.txt
          head -n 20 filelist.txt

      - name: Analyze code with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p reports
          echo "🧠 Анализирую код через ChatGPT..."
          head -c 12000 $(head -n 10 filelist.txt) | \
          curl https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "{
              \"model\": \"gpt-4o-mini\",
              \"messages\": [
                {\"role\": \"system\", \"content\": \"Ты — GitHub Codex аналитик. Проанализируй код и создай отчёт о структуре, зависимостях и возможных проблемах.\"},
                {\"role\": \"user\", \"content\": \"$(head -c 12000 $(head -n 10 filelist.txt))\"}
              ]
            }" \
          | jq -r '.choices[0].message.content' > reports/analysis_codex_result.md
          echo "✅ Отчёт сохранён в reports/analysis_codex_result.md"

      - name: Commit and push report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "ChatGPT Codex Bot"
          git config --global user.email "codex-bot@openai.com"
          git add reports/analysis_codex_result.md
          git commit -m "Add analysis report for ${{ github.event.inputs.branch }}" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}


